### ISSUE TITLE
希望能设置上层代理处理 https 请求

### ISSUE THREAD

**Issue by cocoasoda** [yukixz/kcsp-client#1]
功夫网丧心病狂，难以使用 kcsp 登入 dmm

**Comment by yukixz** [comment]
用 pac

On Sunday, 5 June 2016, agentmario notifications@github.com wrote:

> 功夫网丧心病狂，难以使用 kcsp 登入 dmm
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/yukixz/kcsp-client/issues/1, or mute the thread
> https://github.com/notifications/unsubscribe/ADLuwZPZ45u6njbv_1zsH2fG1XcSM7DMks5qImUegaJpZM4IuSbg
> .

## 

_Dazzy Ding_
Email: h@dazzyd.org

**Comment by cocoasoda** [comment]
猴
